### model
model_name_or_path: PATH_TO_MODEL
ref_model: PATH_TO_REF_MODEL
tgdpo_reward_model: PATH_TO_REWARD_MODEL
### method
stage: tgdpo
do_train: true
finetuning_type: full
pref_beta: 0.1
tgdpo_alpha: 0.5
pref_loss: sigmoid 

### dataset
dataset: llama3-8b-instruct-ultrafeedback
eval_dataset: llama3-8b-instruct-ultrafeedback
template: llama3
cutoff_len: 2048
max_prompt_length: 1800
overwrite_cache: true
preprocessing_num_workers: 16
packing: false

### output
output_dir: OUTPUT_DIR
logging_steps: 1
save_steps: 60
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 7.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.0
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50000
